In [7]:
!pip install nltk torch numpy pandas scikit-learn matplotlib seaborn



[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter #Counts frequency of elements in a list or text.
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize  #Splits text into individual words/tokens.
import nltk # Used for NLP tasks like tokenization, stemming, stopword removal, etc

In [9]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [10]:
# NLTK does NOT come with pretrained tokenizers by default.

# Tokenization
nltk.download('punkt')

# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

# Tokenize

In [11]:
tokens = word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

# Build vocabs

In [12]:
#build vocab
vocab = { '<unk>' : 0 }

In [13]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]= len(vocab)

vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [14]:
len(vocab)

284

# Extract sentence from data

In [15]:
input_sentences = document.split('\n')

In [16]:
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [17]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [18]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))


In [19]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

# training Sequence form

In [20]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [21]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [22]:
len(training_sequence)

555

In [23]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [24]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

In [25]:
max(len_list)

25

# Padding

In [26]:
#logic
[0]* (max(len_list)-len(sequence))

[]

In [27]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append( [0]* (max(len_list)-len(sequence)) + sequence  )


In [28]:
len(padded_training_sequence[0])

25

In [29]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [30]:
padded_training_sequence[6]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9]

# tensor convert


In [31]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype=torch.long)

In [32]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [33]:
X = padded_training_sequence[:, :-1]

In [34]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [35]:
y = padded_training_sequence[:,-1]

In [36]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [37]:
len(X)

555

In [38]:
len(y)

555

# Custom Dataset and Dataloader

In [39]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx) :
    return self.X[idx], self.y[idx]

In [40]:
dataset = CustomDataset(X,y)

In [41]:
len(dataset)

555

In [42]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [43]:
for input , output in dataloader:
  print(input,output)





tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   5,   6,   7,
           8,   9,  10,  11,  12,  13,   1,  14,  15,  16],
        [  0,   0,   0,   0,   0,   0,   0,   0, 110, 175, 176, 177,  10, 178,
         179,  10,  50, 180, 181,  98,   1, 169, 182,   8],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,  62, 259],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 125, 126],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 147, 148,   1, 103,  10,  11, 149,  89],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 239, 254],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   1,  28, 227,  56, 228,  38,  59, 229,  22],
        [  0,   0,   0,   0

In [44]:
X.shape

torch.Size([555, 24])

In [45]:
y.shape

torch.Size([555])

In [46]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [47]:
X[554]

tensor([158, 223,  10,  11, 278, 281, 282, 139, 283,   8,   4,  50,   1, 172,
        171, 131, 153,   5,   1,   2,   3,  40,   1,  41])

In [48]:
# X[555]

In [49]:
len(dataset)

555

In [50]:
len(vocab)

284

In [51]:
len(dataset[0])

2

In [52]:
len(dataset[0][0])

24

In [53]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

# LSTM Cell

In [54]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output




In [55]:
model = LSTMModel(len(vocab))

In [56]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [57]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [58]:
len(vocab)

284

In [59]:
x = nn.Embedding(284,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150, 284)

In [60]:
len(dataset)

555

In [61]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [62]:
dataset[0][0].shape

torch.Size([24])

In [63]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 24])

In [64]:
a = dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [65]:
x(a)

tensor([[[ 0.3682,  0.2668, -0.0314,  ...,  0.5909,  2.9692, -0.2660],
         [ 0.3682,  0.2668, -0.0314,  ...,  0.5909,  2.9692, -0.2660],
         [ 0.3682,  0.2668, -0.0314,  ...,  0.5909,  2.9692, -0.2660],
         ...,
         [ 0.3682,  0.2668, -0.0314,  ...,  0.5909,  2.9692, -0.2660],
         [ 0.3682,  0.2668, -0.0314,  ...,  0.5909,  2.9692, -0.2660],
         [ 0.1620,  0.9372,  0.0923,  ..., -0.4796, -1.5212,  0.1261]]],
       grad_fn=<EmbeddingBackward0>)

In [66]:
x(a).shape

torch.Size([1, 24, 100])

In [67]:
b = x(a)

In [68]:
y(b)

(tensor([[[-0.0365,  0.0016, -0.1869,  ...,  0.0903, -0.0627, -0.0166],
          [-0.0482, -0.0054, -0.2578,  ...,  0.1161, -0.0896, -0.0179],
          [-0.0523, -0.0124, -0.2904,  ...,  0.1238, -0.0983, -0.0173],
          ...,
          [-0.0594, -0.0347, -0.3277,  ...,  0.1547, -0.0828, -0.0159],
          [-0.0594, -0.0347, -0.3277,  ...,  0.1548, -0.0828, -0.0159],
          [ 0.0332,  0.0268,  0.1165,  ...,  0.0031, -0.0732,  0.0987]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[ 3.3192e-02,  2.6822e-02,  1.1649e-01,  1.5053e-01,  2.6996e-03,
            -3.8966e-02,  2.5638e-01,  8.9680e-02,  1.8564e-01, -1.5057e-01,
            -2.6214e-03,  1.1520e-01, -2.0166e-01,  4.3866e-02, -8.9969e-02,
             5.2192e-02, -1.5374e-01,  3.2871e-02, -2.1542e-01,  2.4527e-02,
             1.7923e-01, -1.8794e-01, -1.1545e-01,  1.7746e-01, -6.6573e-02,
            -7.5464e-02, -2.4471e-01,  1.5300e-02, -1.2554e-01,  2.2818e-01,
            -3.1574e-01,  6.7596e-02, -1.7293e-01,

In [69]:
len(y(b))

2

In [70]:
c ,d = y(b)

In [71]:
c.shape  #Set of all intermediate hidden state

torch.Size([1, 24, 150])

In [72]:
len(y(b))

2

In [73]:
len(d)

2

In [74]:
e, f = d


In [75]:
e.shape  #Cell state

torch.Size([1, 1, 150])

In [76]:
f.shape

torch.Size([1, 1, 150])

In [77]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

In [78]:
f_temp = f.squeeze(0)

In [79]:
z(f_temp)

tensor([[ 2.6550e-01, -1.4882e-01,  7.1234e-02, -1.5710e-01,  3.5098e-01,
          3.6787e-01,  7.0087e-02,  3.6948e-02, -1.7764e-01, -3.3332e-02,
         -1.8457e-01,  1.7701e-01, -2.6937e-01, -1.9075e-01,  1.5174e-01,
          1.7465e-01,  1.1855e-01, -9.4517e-02, -2.8683e-01, -5.9560e-02,
         -5.0526e-02,  1.9816e-01,  3.0411e-01, -7.7308e-02,  1.7621e-01,
         -1.1509e-01,  4.0353e-02, -2.8685e-01, -2.4044e-01,  1.3170e-01,
          2.1478e-02,  2.6895e-01,  1.1725e-01,  1.3923e-01, -7.0683e-02,
         -9.6719e-02, -1.7353e-01, -5.8198e-02,  1.5816e-01, -1.4097e-01,
          2.5423e-01,  5.4989e-02, -1.3511e-01,  1.5642e-01,  4.8339e-02,
          1.6473e-01, -2.2226e-01,  2.6085e-01, -4.3322e-02, -1.1518e-02,
          6.6768e-02,  1.5592e-02,  5.6718e-01,  4.9267e-02, -9.0087e-02,
          1.3736e-01, -3.0670e-01, -1.6889e-01, -1.3373e-01,  1.2732e-01,
          1.4149e-01, -4.7365e-01,  4.5137e-02,  2.2475e-01, -1.0285e-01,
         -2.0615e-01,  4.3349e-02,  3.

In [80]:
len(f_temp[0])

150

In [81]:
len(z(f_temp)[0])

284

In [82]:
len(vocab)

284

In [83]:
for batch_x , batch_y in dataloader:
  print(batch_x, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,  33,  34,  35,
          36,   1,  37,  38,   1,  39,   3,  40,   1,  41],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   6,  33,  34],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  77, 190,
          10,   1,   3, 191, 192, 193, 194, 195,  88, 196],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0, 108],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 204, 185],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  28, 199, 200,  50,  79, 201, 202, 203],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   1],
        [  0,   0,   0,   0

# Training loop

In [84]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 101.0324
Epoch: 2, Loss: 94.5823
Epoch: 3, Loss: 87.4362
Epoch: 4, Loss: 82.5599
Epoch: 5, Loss: 77.5447
Epoch: 6, Loss: 72.8005
Epoch: 7, Loss: 67.2027
Epoch: 8, Loss: 61.3885
Epoch: 9, Loss: 56.8244
Epoch: 10, Loss: 50.8842
Epoch: 11, Loss: 46.2477
Epoch: 12, Loss: 41.1993
Epoch: 13, Loss: 36.9111
Epoch: 14, Loss: 33.1985
Epoch: 15, Loss: 29.6723
Epoch: 16, Loss: 26.2686
Epoch: 17, Loss: 23.2715
Epoch: 18, Loss: 20.6175
Epoch: 19, Loss: 18.0958
Epoch: 20, Loss: 16.2360
Epoch: 21, Loss: 14.5296
Epoch: 22, Loss: 12.9688
Epoch: 23, Loss: 11.7155
Epoch: 24, Loss: 10.6086
Epoch: 25, Loss: 9.6335
Epoch: 26, Loss: 8.7977
Epoch: 27, Loss: 7.9372
Epoch: 28, Loss: 7.3545
Epoch: 29, Loss: 6.7426
Epoch: 30, Loss: 6.2417
Epoch: 31, Loss: 5.7632
Epoch: 32, Loss: 5.3408
Epoch: 33, Loss: 5.0410
Epoch: 34, Loss: 4.9887
Epoch: 35, Loss: 4.5046
Epoch: 36, Loss: 4.2898
Epoch: 37, Loss: 4.1473
Epoch: 38, Loss: 3.9527
Epoch: 39, Loss: 3.7488
Epoch: 40, Loss: 3.5610
Epoch: 41, Loss: 3.5216


# Prediction

In [85]:
max(len_list)

25

In [86]:
#logic
[0]* (25-len(numerical_text)) + numerical_text

NameError: name 'numerical_text' is not defined

In [ ]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)


  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)


  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]





In [ ]:
prediction(model,vocab,"Hi how are you the station was")

'Hi how are you the station was nearly'

In [ ]:
len(vocab)

284

In [ ]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

# Generate Automatically

In [ ]:
import time
num_tokens = 20
input_text= 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

# Accuracy calculation

In [ ]:
def calculate_accuracy(model,dataloader,device):

  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      # print(len(batch_x)),len(batch_y)
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      #get model prediction
      output = model(batch_x)

      # print(len(output[0]))

      #get the predictec word indices

      _, predicted = torch.max(output,dim=1)

      # print("printing predicted",predicted)

      #compare wityh actual label

      # print("printing y lable",batch_y)

      # print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

      # print(correct)
      # print("working with total",batch_y.size())
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy






In [ ]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 96.94%
